resolver: lts-9.0

packages:
- '.'

extra-deps:
- scotty-tls-0.4.1
- rss-3000.2.0.6
- HaXml-1.25.3

flags: {}

extra-package-dbs: []

# Control whether we use the GHC we find on the path
# system-ghc: true

# Allow a newer minor version of GHC than the snapshot specifies
compiler-check: newer-minor
