flags:
  text:
    integer-simple: false
packages:
- '.'
extra-deps:
- aeson-0.10.0.0
- aeson-pretty-0.7.2
- ansi-terminal-0.6.2.3
- appar-0.1.4
- asn1-encoding-0.9.3
- asn1-parse-0.9.4
- asn1-types-0.3.1
- async-2.0.2
- attoparsec-0.13.0.1
- auto-update-0.1.2.2
- base64-bytestring-1.0.0.1
- bifunctors-5
- blaze-builder-0.4.0.1
- blaze-html-0.8.1.1
- blaze-markup-0.7.0.3
- byteable-0.1.1
- byteorder-1.0.4
- bytestring-builder-0.10.6.0.0
- case-insensitive-1.2.0.5
- cereal-0.4.1.1
- cipher-aes-0.2.11
- cmdargs-0.10.13
- conduit-1.2.5
- conduit-extra-1.1.9.1
- cookie-0.4.1.6
- cprng-aes-0.6.1
- crypto-cipher-types-0.0.9
- crypto-random-0.0.9
- cryptonite-0.7
- css-text-0.1.2.1
- data-default-0.5.3
- data-default-class-0.0.1
- data-default-instances-base-0.0.1
- data-default-instances-containers-0.0.1
- data-default-instances-dlist-0.0.1
- data-default-instances-old-locale-0.0.1
- dlist-0.7.1.2
- easy-file-0.2.1
- exceptions-0.8.0.2
- fast-logger-2.4.1
- hashable-1.2.3.3
- hex-0.1.2
- hourglass-0.2.9
- http-date-0.0.6.1
- http-types-0.8.6
- http2-1.1.0
- iproute-1.7.0
- lifted-base-0.2.3.6
- markdown-0.1.13.2
- memory-0.10
- mime-types-0.1.0.6
- mmorph-1.0.4
- monad-control-1.0.0.4
- mtl-2.2.1
- mwc-random-0.13.3.2
- nats-1
- network-2.6.2.1
- network-uri-2.6.0.3
- old-locale-1.0.0.7
- old-time-1.1.0.3
- parsec-3.1.9
- pem-0.2.2
- primitive-0.6.1.0
- random-1.1
- regex-base-0.93.2
- regex-compat-0.95.1
- regex-posix-0.95.2
- resourcet-1.1.6
- scientific-0.3.4.0
- scotty-0.10.2
- scotty-tls-0.4.0
- securemem-0.1.9
- semigroups-0.17.0.1
- simple-sendfile-0.2.21
- stm-2.4.4
- streaming-commons-0.1.14.2
- stringsearch-0.3.6.6
- syb-0.6
- tagged-0.8.1
- tagsoup-0.13.3
- text-1.2.1.3
- tls-1.3.3
- transformers-base-0.4.4
- transformers-compat-0.4.0.4
- unix-compat-0.4.1.4
- unix-time-0.3.5
- unordered-containers-0.2.5.1
- utf8-string-1.0.1.1
- vault-0.3.0.4
- vector-0.11.0.0
- void-0.7.1
- wai-3.0.4.0
- wai-extra-3.0.10
- wai-logger-2.2.4.1
- warp-3.1.4
- warp-tls-3.1.3
- word8-0.1.2
- x509-1.6.3
- x509-store-1.6.1
- x509-validation-1.6.3
- xss-sanitize-0.3.5.6
- zlib-0.6.1.1
resolver: ghc-7.10.2
