resolver: lts-7.0

packages:
- '.'

extra-deps:
- scotty-tls-0.4.1

flags: {}

extra-package-dbs: []

# Control whether we use the GHC we find on the path
# system-ghc: true

# Allow a newer minor version of GHC than the snapshot specifies
compiler-check: newer-minor
