version: 2.1
jobs:
  build:
    docker:
      - image: fpco/stack-build:lts-10.6
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          name: Restore Cached Dependencies
          keys:
            - cci-demo-haskell-v1-{{ checksum "stack.yaml" }}-{{ checksum "hablog.cabal" }}
      - run:
          name: Workaround for GCC bug affecting static compilation
          command: |
            # More info about this workaround:
            # - https://www.fpcomplete.com/blog/2016/10/static-compilation-with-stack
            # - https://bugs.launchpad.net/ubuntu/+source/gcc-4.4/+bug/640734
            cp /usr/lib/gcc/x86_64-linux-gnu/5/crtbeginT.o /usr/lib/gcc/x86_64-linux-gnu/5/crtbeginT.o.orig
            cp /usr/lib/gcc/x86_64-linux-gnu/5/crtbeginS.o /usr/lib/gcc/x86_64-linux-gnu/5/crtbeginT.o
      - run:
          name: Configure Stack
          command: |
            stack config set system-ghc --global true
      - run:
          name: Statically compile Blog
          command: |
            stack --local-bin-path ~/app/dist install --ghc-options '-optl-static -fPIC'
      - run:
          name: Run tests
          command: |
            stack test
      - save_cache:
          name: Cache Dependencies
          key: cci-demo-haskell-v1-{{ checksum "stack.yaml" }}-{{ checksum "hablog.cabal" }}
          paths:
            - "/root/.stack"
            - ".stack-work"
      - store_artifacts:
          path: ~/app/dist
      - run:
          name: Setup Heroku
          command: bash .circleci/setup-heroku.sh
      - add_ssh_keys:
          fingerprints:
            - "34:e6:c0:32:7f:74:bf:19:0a:3a:09:52:e6:6e:12:52"
      - deploy:
          name: Deploy Master to Heroku
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              git config --global user.email "m.doughty@hushmail.com"
              git config --global user.name "Matt Doughty"
              git add -f dist
              git commit -m "Deployment: Add dist folder"
              git push -f heroku master
            fi
